name: fijkplayer
description: A Video Player Flutter plugin based on ijkplayer, support most popular protocols and codecs
version: 0.9.0
homepage: https://fijkplayer.befovy.com
repository: https://github.com/befovy/fijkplayer
issue_tracker: https://github.com/befovy/fijkplayer/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.befovy.fijkplayer
    pluginClass: FijkPlugin